site_name: ciscoaxl
theme:
  name: readthedocs
nav:
  - Installation: index.md
  - Introduction: intro.md
  - API:
    - Users: users.md
    - Devices: devices.md
    - Trunks: trunks.md
    - Locations: locations.md
    - Regions: regions.md
    - Device Pools: devicepools.md
    - Partitions: partitions.md
    - Calling Search Spaces: css.md
    - Translation Patterns: translations.md
    - Route Patterns: routepatterns.md
  
repo_url: https://github.com/levensailor/ciscoaxl
plugins:
  - search
