site_name: ciscoaxl
theme:
  name: readthedocs
nav:
  - Installation: index.md
  - Introduction: intro.md
  - API: api.md
  - Examples: examples.md

  
repo_url: https://github.com/levensailor/ciscoaxl
plugins:
  - search
