site_name: ciscoaxl
theme:
  name: readthedocs
nav:
  - Installation: index.md
  - Introduction: intro.md
  - API:
    - Users: endpoints/users.md
    - Devices: endpoints/devices.md
    - Trunks: endpoints/trunks.md
    - Locations: endpoints/locations.md
    - Regions: endpoints/regions.md
    - Device Pools: endpoints/devicepools.md
    - Partitions: endpoints/partitions.md
    - Calling Search Spaces: endpoints/css.md
    - Translation Patterns: endpoints/translations.md
    - Route Patterns: endpoints/routepatterns.md
  
repo_url: https://github.com/levensailor/ciscoaxl
plugins:
  - search
