site_name: ciscoaxl
theme:
  name: readthedocs
nav:
  - Installation: index.md
  - Introduction: intro.md
  - Examples: examples.md
  - API Reference:
    - Users: users.md
    - Phones: phones.md
    - Device Profiles: deviceprofiles.md
    - Device Pools: devicepools.md
    - Directory Numbers: dn.md
    - Partitions: partitions.md
    - Calling Search Spaces: css.md
    - Gateways: gateway.md
    - Trunks: trunks.md
    - Locations: locations.md
    - Regions: regions.md
    - Translation Patterns: translations.md
    - Route Patterns: routepatterns.md
    - CTI Route Points: cti.md
    - Media Resources: media.md
    - Call Park: callpark.md
    - Call Pickup: callpickup.md
    - Voicemail: vmprofile.md
    - Route Lists: routelist.md
    - Route Groups: routegroup.md
    - Hunting: hunt.md
    - Remote Destinations: rd.md
    - Route Plans: routeplans.md
    - Transformations: xform.md
    - Call Manager Groups: cm.md
    - LDAP: ldap.md
    - SQL: sql.md
  
repo_url: https://github.com/levensailor/ciscoaxl
plugins:
  - search
