site_name: ciscoaxl
theme:
  name: readthedocs
nav:
  - Installation: index.md
  - Introduction: intro.md
  - Examples: examples.md
  - API Reference:
    - Users: users.md
    - Devices: phones.md
    - Device Pools: devicepools.md
    - Directory Numbers: dn.md
    - Partitions: partitions.md
    - Calling Search Spaces: css.md
    - Trunks and Gateways: trunks.md
    - Locations: locations.md
    - Regions: regions.md
    - Translation Patterns: translations.md
    - Transformation Patterns: xform.md
    - Route Patterns: routepatterns.md
    - CTI Route Points: cti.md
    - Media Resources: media.md
    - Call Park: callpark.md
    - Call Pickup: callpickup.md
    - Call Routing: routelist.md
    - Call Hunting: hunt.md
    - Voicemail: vmprofile.md
    - Remote Destinations: rd.md
    - Call Manager Groups: cm.md
    - LDAP: ldap.md
    - SQL: sql.md
  
repo_url: https://github.com/levensailor/ciscoaxl
plugins:
  - search
