site_name: ciscoaxl
theme:
  name: readthedocs
nav:
  - Installation: index.md
  - Introduction: intro.md
  - Examples: examples.md
  - API Reference:
    - Users: users.md
    - Phones: phones.md
  
repo_url: https://github.com/levensailor/ciscoaxl
plugins:
  - search
